# Generated by Django 3.1 on 2020-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_number',
            field=models.IntegerField(default=2),
        ),
    ]
