# Generated by Django 3.1 on 2020-08-30 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_xuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vdq',
            field=models.ManyToManyField(blank=True, related_name='user_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
