# Generated by Django 3.1 on 2020-08-30 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_question_vdq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='vdq',
            field=models.ManyToManyField(related_name='user_voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xuser',
            name='voted_question',
            field=models.ManyToManyField(to='polls.Question'),
        ),
    ]
